export const HttpMethod = {
  Get: 'GET',
  Post: 'POST',
  Put: 'PUT',
  Patch: 'PATCH',
  Delete: 'DELETE',
  Options: 'OPTIONS',
  Head: 'HEAD',
} as const;

export const ContentType = {
  Json: 'application/json',
  Yaml: 'application/yaml',
  Text: 'text/plain',
  Html: 'text/html',
  Css: 'text/css',
  Javascript: 'application/javascript',
  FormUrlencoded: 'application/x-www-form-urlencoded',
  MultipartFormData: 'multipart/form-data',
  OctetStream: 'application/octet-stream',
} as const;

export const HeaderField = {
  Location: 'location',
  ContentType: 'content-type',
  ContentLength: 'content-length',
  ContentEncoding: 'content-encoding',
  CacheControl: 'cache-control',
  XForwardedFor: 'x-forwarded-for',
  XRealIp: 'x-real-ip',
  RequestId: 'x-request-id',
  Origin: 'origin',
  AcceptEncoding: 'accept-encoding',
  Vary: 'vary',
  ETag: 'etag',
  AccessControlAllowOrigin: 'access-control-allow-origin',
  AccessControlAllowCredentials: 'access-control-allow-credentials',
  AccessControlAllowMethods: 'access-control-allow-methods',
  AccessControlAllowHeaders: 'access-control-allow-headers',
  AccessControlMaxAge: 'access-control-max-age',
  AccessControlExposeHeaders: 'access-control-expose-headers',
  ContentDisposition: 'content-disposition',
  AccessControlRequestMethod: 'access-control-request-method',
  AccessControlRequestHeaders: 'access-control-request-headers',
  NoCompress: 'x-no-compress',
  Range: 'range',
} as const;
