export const textEncoder = new TextEncoder();

export const Protocol = {
  Http: 'http',
  Https: 'https',
} as const;

export const HttpMethod = {
  Get: 'GET',
  Post: 'POST',
  Put: 'PUT',
  Patch: 'PATCH',
  Delete: 'DELETE',
  Options: 'OPTIONS',
  Head: 'HEAD',
} as const;

export const ContentType = {
  Json: 'application/json',
  Yaml: 'application/yaml',
  Text: 'text/plain',
  Html: 'text/html',
  Css: 'text/css',
  Javascript: 'application/javascript',
  FormUrlencoded: 'application/x-www-form-urlencoded',
  MultipartFormData: 'multipart/form-data',
  OctetStream: 'application/octet-stream',
} as const;

export const HeaderField = {
  Location: 'location',
  ContentType: 'content-type',
  ContentLength: 'content-length',
  ContentEncoding: 'content-encoding',
  CacheControl: 'cache-control',
  XForwardedFor: 'x-forwarded-for',
  XForwardedProto: 'x-forwarded-proto',
  XRealIp: 'x-real-ip',
  RequestId: 'x-request-id',
  XContentTypeOptions: 'x-content-type-options',
  XDnsPrefetchControl: 'x-dns-prefetch-control',
  XDownloadOptions: 'x-download-options',
  XFrameOptions: 'x-frame-options',
  XPermittedCrossDomainPolicies: 'x-permitted-cross-domain-policies',
  XXssProtection: 'x-xss-protection',
  XPoweredBy: 'x-powered-by',
  ExpectCt: 'expect-ct',
  ContentSecurityPolicy: 'content-security-policy',
  ContentSecurityPolicyReportOnly: 'content-security-policy-report-only',
  CrossOriginEmbedderPolicy: 'cross-origin-embedder-policy',
  CrossOriginOpenerPolicy: 'cross-origin-opener-policy',
  CrossOriginResourcePolicy: 'cross-origin-resource-policy',
  OriginAgentCluster: 'origin-agent-cluster',
  ReferrerPolicy: 'referrer-policy',
  StrictTransportSecurity: 'strict-transport-security',
  PermissionsPolicy: 'permissions-policy',
  Origin: 'origin',
  AcceptEncoding: 'accept-encoding',
  Vary: 'vary',
  ETag: 'etag',
  AccessControlAllowOrigin: 'access-control-allow-origin',
  AccessControlAllowCredentials: 'access-control-allow-credentials',
  AccessControlAllowMethods: 'access-control-allow-methods',
  AccessControlAllowHeaders: 'access-control-allow-headers',
  AccessControlMaxAge: 'access-control-max-age',
  AccessControlExposeHeaders: 'access-control-expose-headers',
  ContentDisposition: 'content-disposition',
  AccessControlRequestMethod: 'access-control-request-method',
  AccessControlRequestHeaders: 'access-control-request-headers',
  NoCompress: 'x-no-compress',
  Range: 'range',
} as const;
