[package]
name = "bunner-core-logger"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1.18"
libc = "0.2"

[dev-dependencies]
libloading = "0.7"
